-- SQL Schema updates for Affiliate System
-- Run this in Supabase SQL Editor

-- 1. Add commission column to products if not exists
ALTER TABLE products ADD COLUMN IF NOT EXISTS commission NUMERIC DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';

-- 2. Create affiliate_users table
CREATE TABLE IF NOT EXISTS affiliate_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    affiliate_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    password_hash TEXT NOT NULL,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create affiliate_tracking_clicks table
CREATE TABLE IF NOT EXISTS affiliate_tracking_clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    affiliate_id TEXT NOT NULL,
    product_name TEXT,
    tracking_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3.1 Create affiliate_commissions table
CREATE TABLE IF NOT EXISTS affiliate_commissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT UNIQUE NOT NULL,
    affiliate_id TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'unpaid', -- unpaid, paid
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create orders table if not exists (to ensure columns match)
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT UNIQUE NOT NULL,
    user_id TEXT,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    phone2 TEXT,
    city TEXT,
    city_type TEXT,
    shipping_cost NUMERIC DEFAULT 0,
    total_amount NUMERIC NOT NULL,
    address TEXT,
    location_link TEXT,
    affiliate_id TEXT,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Create order_products table if not exists
CREATE TABLE IF NOT EXISTS order_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id BIGINT,
    product_name TEXT NOT NULL,
    quantity INTEGER DEFAULT 1,
    price NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Enable RLS and set policies
ALTER TABLE affiliate_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliate_tracking_clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_products ENABLE ROW LEVEL SECURITY;

-- Allow public read access to these tables (for our API proxy to work)
-- Note: Our Vercel API uses service key or anon key with these policies
CREATE POLICY "Public read affiliate_users" ON affiliate_users FOR SELECT USING (true);
CREATE POLICY "Public insert affiliate_users" ON affiliate_users FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update affiliate_users" ON affiliate_users FOR UPDATE USING (true);

CREATE POLICY "Public insert affiliate_tracking_clicks" ON affiliate_tracking_clicks FOR INSERT WITH CHECK (true);
CREATE POLICY "Public read affiliate_tracking_clicks" ON affiliate_tracking_clicks FOR SELECT USING (true);

CREATE POLICY "Public read affiliate_commissions" ON affiliate_commissions FOR SELECT USING (true);
CREATE POLICY "Public insert affiliate_commissions" ON affiliate_commissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update affiliate_commissions" ON affiliate_commissions FOR UPDATE USING (true);

CREATE POLICY "Public read orders" ON orders FOR SELECT USING (true);
CREATE POLICY "Public insert orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update orders" ON orders FOR UPDATE USING (true);

CREATE POLICY "Public read order_products" ON order_products FOR SELECT USING (true);
CREATE POLICY "Public insert order_products" ON order_products FOR INSERT WITH CHECK (true);
