-- Create aliexpress_products table
CREATE TABLE IF NOT EXISTS public.aliexpress_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    name_ar TEXT NOT NULL,
    description_ar TEXT,
    image_url TEXT NOT NULL,
    price NUMERIC NOT NULL,
    currency TEXT DEFAULT 'USD',
    affiliate_link TEXT NOT NULL,
    source_product_id TEXT UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for fast lookup
CREATE INDEX IF NOT EXISTS idx_aliexpress_products_slug ON public.aliexpress_products(slug);
CREATE INDEX IF NOT EXISTS idx_aliexpress_products_source_product_id ON public.aliexpress_products(source_product_id);
CREATE INDEX IF NOT EXISTS idx_aliexpress_products_is_active ON public.aliexpress_products(is_active);

-- Enable RLS
ALTER TABLE public.aliexpress_products ENABLE ROW LEVEL SECURITY;

-- Allow public read access to active products
CREATE POLICY "Allow public read access to active aliexpress products"
ON public.aliexpress_products FOR SELECT
USING (is_active = true);

-- Allow full access for service_role or admin proxy
CREATE POLICY "Allow service role full access to aliexpress products"
ON public.aliexpress_products FOR ALL
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');
