-- Commission Settings Setup
-- Run this in Supabase SQL Editor to allow managing settings from the Admin Panel

-- 1. Ensure admin_settings table exists (it should, but just in case)
CREATE TABLE IF NOT EXISTS admin_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Drop restrictive policies if they exist
DROP POLICY IF EXISTS "Admin settings no access" ON admin_settings;

-- 3. Create policies to allow access (using anon key via proxy)
CREATE POLICY "Enable read for all" ON admin_settings FOR SELECT USING (true);
CREATE POLICY "Enable insert for all" ON admin_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all" ON admin_settings FOR UPDATE USING (true);

-- 4. Initialize default values
INSERT INTO admin_settings (key, value) VALUES
('commission_threshold', '100000'),
('commission_low_rate', '8'),
('commission_high_rate', '6')
ON CONFLICT (key) DO NOTHING;
