
-- نظام تتبع المسوقين الكامل - متجر زونا
-- تنفيذ هذا السكريبت في محرر SQL الخاص بـ Supabase

-- 1. جدول المسوقين
CREATE TABLE IF NOT EXISTS affiliate_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    affiliate_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT UNIQUE,
    password TEXT NOT NULL,
    status TEXT DEFAULT 'active', -- active, inactive
    total_clicks INTEGER DEFAULT 0,
    total_orders INTEGER DEFAULT 0,
    registration_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. جدول النقرات
CREATE TABLE IF NOT EXISTS affiliate_clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    affiliate_id TEXT REFERENCES affiliate_users(affiliate_id),
    click_date DATE DEFAULT CURRENT_DATE,
    click_count INTEGER DEFAULT 1,
    product_name TEXT,
    tracking_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. جدول الطلبات (الجدول الرئيسي)
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT UNIQUE NOT NULL,
    user_id TEXT,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    phone2 TEXT,
    city TEXT,
    city_type TEXT, -- cod, prepaid
    shipping_cost NUMERIC DEFAULT 0,
    total_amount NUMERIC NOT NULL,
    address TEXT,
    location_lat NUMERIC,
    location_lng NUMERIC,
    location_link TEXT,
    payment_type TEXT,
    affiliate_id TEXT DEFAULT 'direct',
    status TEXT DEFAULT 'new', -- new, processing, shipped, delivered, completed, cancelled
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. جدول منتجات الطلبات
CREATE TABLE IF NOT EXISTS order_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT REFERENCES orders(order_id),
    product_id BIGINT,
    product_name TEXT,
    quantity INTEGER DEFAULT 1,
    price NUMERIC,
    warehouse TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. جدول عمولات المسوقين
CREATE TABLE IF NOT EXISTS affiliate_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    affiliate_id TEXT REFERENCES affiliate_users(affiliate_id),
    order_id TEXT REFERENCES orders(order_id),
    commission NUMERIC DEFAULT 0,
    commission_rate TEXT,
    status TEXT DEFAULT 'pending', -- pending (معلقة), paid (مدفوعة)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. إضافة أعمدة إضافية لجدول المنتجات
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='commission') THEN
        ALTER TABLE products ADD COLUMN commission INTEGER DEFAULT 0;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='is_out_of_stock') THEN
        ALTER TABLE products ADD COLUMN is_out_of_stock BOOLEAN DEFAULT FALSE;
    END IF;
END $$;

-- 7. تفعيل سياسات الأمان (RLS) للوصول العام (Anon Key)
ALTER TABLE affiliate_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliate_clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliate_orders ENABLE ROW LEVEL SECURITY;

-- سياسات الوصول (لأغراض العرض التوضيحي، يفضل تخصيصها أكثر في الإنتاج)
CREATE POLICY "Public Access" ON affiliate_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON affiliate_clicks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON order_products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access" ON affiliate_orders FOR ALL USING (true) WITH CHECK (true);

-- 8. فهارس لتحسين الأداء
CREATE INDEX IF NOT EXISTS idx_affiliate_id ON affiliate_users(affiliate_id);
CREATE INDEX IF NOT EXISTS idx_order_affiliate ON orders(affiliate_id);
CREATE INDEX IF NOT EXISTS idx_aff_order_status ON affiliate_orders(status);
