-- Supabase SQL for ZOONA Products Management
-- Run this in Supabase SQL Editor

-- =============================================
-- Table: products
-- =============================================
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    old_price NUMERIC,
    discount INTEGER,
    image TEXT,
    category TEXT DEFAULT 'عام',
    description TEXT,
    warehouse TEXT DEFAULT 'الخرطن',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Delivery cities data (stored as JSON)
    delivery_cities JSONB DEFAULT '[]'::jsonb
);

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read products
CREATE POLICY "Enable read access for all users" ON products
    FOR SELECT
    USING (true);

-- Policy: Only authenticated users can insert/update/delete
-- (We will use anon key but with password check in client)
CREATE POLICY "Enable insert for authenticated" ON products
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Enable update for authenticated" ON products
    FOR UPDATE
    USING (true);

CREATE POLICY "Enable delete for authenticated" ON products
    FOR DELETE
    USING (true);

-- =============================================
-- Table: admin_settings
-- =============================================
CREATE TABLE IF NOT EXISTS admin_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert admin password
INSERT INTO admin_settings (key, value) VALUES ('admin_password', 'zoona2025')
    ON CONFLICT (key) DO NOTHING;

-- RLS for admin_settings (no public access)
ALTER TABLE admin_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin settings no access" ON admin_settings
    FOR ALL
    USING (false)
    WITH CHECK (false);

-- =============================================
-- Index for faster queries
-- =============================================
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_active ON products(created_at DESC);

-- =============================================
-- Function to verify admin password
-- =============================================
CREATE OR REPLACE FUNCTION verify_admin_password(password TEXT)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM admin_settings 
        WHERE key = 'admin_password' AND value = password
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================
-- Sample products with delivery cities
-- =============================================
INSERT INTO products (name, price, old_price, discount, image, category, description, warehouse, delivery_cities) VALUES
('آيباد الأطفال الذكي', 190000, 220000, 14, 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=400', 'ألعاب أطفال', 'آيباد تعليمي للأطفال بشاشة 10 بوصة', 'الخرطم',
'[{"name":"الخرطم","price":0,"type":"cod"},{"name":"أم درمان","price":0,"type":"cod"},{"name":"بحري","price":0,"type":"cod"},{"name":"جازابورا","price":2500,"type":"cod"},{"name":"سنار","price":3000,"type":"cod"},{"name":"القضارف","price":3500,"type":"cod"},{"name":"كسلا","price":3000,"type":"prepaid"},{"name":"ود مدني","price":2000,"type":"prepaid"},{"name":"عطبار","price":2500,"type":"prepaid"}]'),
('سامسونج A15 128GB', 380000, 420000, 10, 'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=400', 'موبايلات', 'هاتف سامسونج جلاكسي A15 بذاكرة 128GB', 'الخرطم',
'[{"name":"الخرطم","price":0,"type":"cod"},{"name":"أم درمان","price":0,"type":"cod"},{"name":"بحري","price":0,"type":"cod"},{"name":"جازابورا","price":2500,"type":"cod"},{"name":"سنار","price":3000,"type":"cod"},{"name":"القضارف","price":3500,"type":"cod"},{"name":"كسلا","price":3000,"type":"prepaid"},{"name":"ود مدني","price":2000,"type":"prepaid"},{"name":"عطبار","price":2500,"type":"prepaid"}]'),
('سماعات لاسلكية بلوتوث', 45000, 65000, 31, 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=400', 'إكسسوارات موبايلات', 'سماعات TWS لاسلكية بجودة صوت عالية', 'الخرطم',
'[{"name":"الخرطم","price":0,"type":"cod"},{"name":"أم درمان","price":0,"type":"cod"},{"name":"بحري","price":0,"type":"cod"},{"name":"جازابورا","price":1500,"type":"cod"},{"name":"سنار","price":2000,"type":"cod"},{"name":"القضارف","price":2500,"type":"cod"},{"name":"كسلا","price":2000,"type":"prepaid"},{"name":"ود مدني","price":1000,"type":"prepaid"},{"name":"عطبار","price":1500,"type":"prepaid"}]'),
('شاحن سريع 65W USB-C', 28000, 35000, 20, 'https://images.pexels.com/photos/4219654/pexels-photo-4219654.jpeg?auto=compress&cs=tinysrgb&w=400', 'إكسسوارات موبايلات', 'شاحن سريع 65 واط', 'الخرطم',
'[{"name":"الخرطم","price":0,"type":"cod"},{"name":"أم درمان","price":0,"type":"cod"},{"name":"بحري","price":0,"type":"cod"},{"name":"جازابورا","price":1500,"type":"cod"},{"name":"سنار","price":2000,"type":"cod"},{"name":"القضارف","price":2500,"type":"cod"},{"name":"كسلا","price":2000,"type":"prepaid"},{"name":"ود مدني","price":1000,"type":"prepaid"},{"name":"عطبار","price":1500,"type":"prepaid"}]'),
('لابتوب HP Core i5 جيل 12', 980000, 1100000, 11, 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=400', 'أجهزة إلكترونية', 'لابتوب HP بمعالج Core i5', 'الخرطم',
'[{"name":"الخرطم","price":0,"type":"cod"},{"name":"أم درمان","price":0,"type":"cod"},{"name":"بحري","price":0,"type":"cod"},{"name":"جازابورا","price":5000,"type":"cod"},{"name":"سنار","price":6000,"type":"cod"},{"name":"القضارف","price":7000,"type":"cod"},{"name":"كسلا","price":5000,"type":"prepaid"},{"name":"ود مدني","price":3000,"type":"prepaid"},{"name":"عطبار","price":4000,"type":"prepaid"}]')
ON CONFLICT DO NOTHING;

-- =============================================
-- Function to get all products (for public API)
-- =============================================
CREATE OR REPLACE FUNCTION get_products()
RETURNS SETOF products AS $$
    SELECT * FROM products ORDER BY id DESC;
$$ LANGUAGE sql SECURITY DEFINER;

-- =============================================
-- Function to verify admin and get settings
-- =============================================
CREATE OR REPLACE FUNCTION get_admin_setting(key_name TEXT)
RETURNS TEXT AS $$
    SELECT value FROM admin_settings WHERE key = key_name;
$$ LANGUAGE sql SECURITY DEFINER;